[project]
name = "mjlab-go2"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["mjlab"]

[tool.uv.sources]
mjlab = { git = "https://github.com/mujocolab/mjlab", rev = "main" }
